ID_NEXTION_ORDER_TEXT = "t1"
ID_NEXTION_ORDER_PERCENTAGE = "t0"
ID_NEXTION_ORDER_PRICES_TEXT = "t3"
ID_NEXTION_TOTAL_PRICE_TEXT = "t2"
ID_NEXTION_PROCESS_BAR_NUM = "j0"
ID_NEXTION_QR = "qr0"
NEXTION_LINE_CHANGE = '\r'